version: '3.8'
services:
  db:
    image: mysql:5.7
    container_name: event2all-db
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=sql123
      - MYSQL_DATABASE=event2all
    restart: always
    command: --default-authentication-plugin=mysql_native_password
  server:
    depends_on:
      - db
    image: giordanocassini/event2all-backend
    container_name: event2all-server
    ports:
      - 3000:3000
    restart: always
  frontend:    
    depends_on:
      - server
    image: giordanocassini/event2all-frontend
    container_name: event2all-frontend
    ports:
      - 3002:8000
    restart: always